[variables]
NIXPACKS_JDK_VERSION = "17"

[phases.build]
cmds = ["cd teknisio_backend && ./gradlew clean build -x check -x test"]

[start]
cmd = "cd teknisio_backend && java -jar build/libs/teknisio-backend-0.0.1-SNAPSHOT.jar"
